name: e-comm
channels:
  - conda-forge
  - defaults
dependencies:
  - imbalanced_learn==0.8.1
  - imblearn==0.0
  - matplotlib==3.3.4
  - numpy==1.19.5
  - pandas==1.3.4
  - Pillow==9.0.1
  - scikit-learn==0.24.2
  - streamlit==1.8.0
  - xgboost==1.5.0
  - pip:
    - streamlit
